#!/bin/sh
arg=$1
name=$2
location="/usr/local/bin/${name:-$(basename "$arg")}"
curl "$arg" | sudo tee "$location" > /dev/null
sudo chmod +x "$location"
test "$INSTALEE_VERBOSE" -lt 3 || echo "Installed $name to $location"
