#!/bin/sh
# Install a package from a local or downloaded .deb-file and remove it
loc="$(basename "$arg")"
case "$1" in
  (http*) wget -O "$loc" "$arg";;
  (*) loc="$arg";;
esac
sudo dpkg -i "$loc"
sudo apt -f install
sudo rm -v "$loc"
